lib/compiler/cli.js
lib/compiler/compiler.js
src/compiler/cli.imba
src/compiler/compiler.imba

a better variant of this judofyr/imba-loader/pull/1

better error reports

---

src/compiler/nodes.imba

The `isStandalone()` helper was _always_ returning `true`.
```js
undefined !== false; //=> true
true !== false; //=> true
```
This means that any `js` Node-methods were always printing their `helper()`function contents, without any way to toggle it on/off.
Resolves #78

Fix `isStandalone` flag logic

---

bin/imbapack

Make imbapack commands platform-safe

---

lib/cli/imbac.js
src/cli/imbac.imba

Fix imbac --stdio/-s option

---

.travis.yml
package-lock.json

`lts/*` tests only against Node.js 10. But 6, 8 and 10 are currently active LTS.

ci: test Node.js 8, 10 and 11

---

readme.md

Also mention the new bi-weekly meeting.

Update the questions section to be community

---

LICENSE
readme.md

- remove duplicated content that has moved to imba.io
- use quote for the intro
- make licensing clear
- use more badges

readme: start polishing it

---

lib/compiler/nodes.js
src/compiler/nodes.imba
test/syntax/conditionals.imba

Fixes: #204 ('not' operator require parentheses)

Handle not operator bug

---

src/compiler/grammar.imba1
src/compiler/nodes.imba1
src/imba/dom.imba
src/imba/events.imba
src/imba/events/selection.imba
src/imba/index.imba
src/imba/internal/fragment.imba
src/imba/internal/scheduler.imba
src/imba/schema.imba
src/imba/ssr.imba
src/imba/svg.imba
test/apps/examples/generate-schema.imba

Initial SSR support

---

bin/imba
bin/imbac
index.d.ts
register.js
rollup.config.js
scripts/bootstrap.compiler2.js
src/compiler/compilation.imba
src/compiler/compiler.imba1
src/compiler/grammar.imba1
src/compiler/helpers.imba1
src/compiler/index.imba1
src/compiler/lexer.imba1
src/compiler/nodes.imba1
src/compiler/rewriter.imba1
src/compiler/sourcemap.imba1
src/imba/dom/asset.imba
src/program/document.imba
src/program/grammar.imba
src/program/scope.imba
src/program/structures.imba
src/program/utils.imba
test/apps/compiler/basics.imba
test/apps/decorators/multiple.imba
test/apps/examples/scrollable-list.imba
test/apps/quirks/object-key-class.imba
test/apps/syntax/class.imba
test/apps/syntax/destructuring-assignment.imba
vendor/jison/jison.js

- Started cleaning up compiler internals - ongoing effort
- Improved type annotations (supported in more places)
- Lots of sourcemapping + vscode tooling related improvements

Internals overhaul

---

readme.md

- correct grammar
- fix `md` formatting
- add punctuation

(docs): update README.md

---

scripts/test-runner.imba
src/bundler/esresolver.imba
src/compiler/nodes.imba1
src/compiler/selparse.imba
src/compiler/styler.imba
src/imba/dom/bind.imba
src/imba/dom/component.imba
src/imba/dom/core.imba
src/imba/dom/core.web.imba
src/imba/dom/fragment.imba
src/imba/dom/indexed-list.imba
src/imba/dom/keyed-list.imba
src/imba/dom/mount.imba
src/imba/dom/teleport.imba
src/imba/dom/transitions.imba
src/imba/imba.imba
src/imba/router/index.imba
test/apps/events/functions.imba
test/apps/rendering/attach.imba
test/apps/rendering/conditionals.imba
test/apps/rendering/dynamic-tag-name-in-loop.imba
test/apps/rendering/forin-else.imba
test/apps/rendering/forin-keyed-else.imba
test/apps/rendering/forin-keyed-fragments.imba
test/apps/rendering/forin-range.imba
test/apps/rendering/form-bindings.imba
test/apps/router/basics.imba
test/apps/slots/slot-text-only.imba
test/spec.imba

Rewritten the way imba inserts and removes dom elements to allow hooking into critical events like when an element is inserted into their parent (needed for transitions++). Also implemented an experimental api for transitions / easing elements. Docs and examples coming on imba.io soon

DOM hooks and transitions

---

src/compiler/nodes.imba1
test/apps/rendering/references.imba

If you have [named elements](https://imba.io/tags/custom-components#named-elements) in your tag declaration, their `$name-of-element` reference will exist immediately, even before render is called.

Precreate named elements

---

packages/imba/src/bundler/bundle.imba
packages/imba/src/bundler/runner.imba
packages/imba/src/compiler/grammar.imba1
packages/imba/src/compiler/nodes.imba1
packages/imba/src/imba/decorators.imba
packages/imba/src/imba/dom/component.imba
packages/imba/src/imba/dom/core.imba
packages/imba/src/imba/dom/core.web.imba
packages/imba/src/imba/hooks.imba
packages/imba/src/imba/imba.imba
packages/imba/src/imba/reactivity.imba
packages/imba/src/imba/scheduler.imba
packages/imba/test/apps/observables/basics.imba
packages/imba/typings/imba.d.ts
packages/typescript-imba-plugin/src/completions.imba

Added a very small and performant mobs-like system for simple state management. Even if it is included in the next alpha it will not be publicly announced or recommended until we've used it a bit more and finalised the design of it. Here is a short post describing how it came to be and what it is meant to solve: https://different-marmoset-f7b.notion.site/State-management-in-Imba-9cbca5658f584ddebab74b2a1c246e2e.
We are going to use this for a large part of the Scrimba data-layer in the months to come. Will likely change and improve as a result of that, but for now the basics do work pretty well.

Observables

---

packages/imba/test/apps/syntax/tagged-template.imba

Add tests for https://github.com/imba/imba/commit/ae8c329d1bb72eec6720108d2847858d092d4ac7
😉

Test the newly added tagged template strings

---

packages/imba-monarch/src/utils.imba
packages/imba-monarch/test/sample.txt
packages/imba/changelog.md
packages/imba/src/compiler/helpers.imba1
packages/imba/test/apps/syntax/units.imba
packages/typescript-imba-plugin/src/checker.imba
packages/typescript-imba-plugin/src/lexer/utils.imba
packages/typescript-imba-plugin/src/util.imba

Discussed these changes offline - a quick addition of time units.

Expand number unit system to minutes, hours, and days

---

packages/e2e-tests/vite-ssr-esm/__tests__/vite-ssr-esm.spec.ts
packages/e2e-tests/vite-ssr-esm/entry-client.imba
packages/e2e-tests/vite-ssr-esm/entry-client.js
packages/e2e-tests/vite-ssr-esm/index.html
packages/e2e-tests/vite-ssr-esm/launch.imba
packages/e2e-tests/vite-ssr-esm/package-lock.json
packages/e2e-tests/vite-ssr-esm/package.json
packages/e2e-tests/vite-ssr-esm/server.imba
packages/e2e-tests/vite-ssr-esm/server.mjs
packages/e2e-tests/vite-ssr-esm/src/entry-client.imba
packages/e2e-tests/vite-ssr-esm/src/entry-client.js
packages/e2e-tests/vite-ssr-esm/src/main.imba
packages/e2e-tests/vite-ssr-esm/vite.config.client.js
packages/e2e-tests/vite-ssr-esm/vite.config.server.js
packages/e2e-tests/vitestGlobalSetup.ts
packages/vite-plugin-imba/README.md
packages/vite-plugin-imba/package-lock.json
packages/vite-plugin-imba/package.json

Fix e2e tests for SSR example and simplify it

fix tests and simplify ssr example

---

.gitignore
packages/e2e-tests/hmr/package-lock.json
packages/e2e-tests/imba-auto-resolve-config-file-js/package-lock.json
packages/e2e-tests/imba-auto-resolve-config-file-json/package-lock.json
packages/e2e-tests/imba-resolve-config-inline/package-lock.json
packages/e2e-tests/package-lock.json
packages/e2e-tests/vite-duplicate-styles-bug/package-lock.json
packages/e2e-tests/vite-import-svg/package-lock.json
packages/e2e-tests/vite-ssr-esm/Readme.md
packages/e2e-tests/vite-ssr-esm/__tests__/vite-ssr-esm.spec.ts
packages/e2e-tests/vite-ssr-esm/launch.imba
packages/e2e-tests/vite-ssr-esm/package-lock.json
packages/e2e-tests/vite-ssr-esm/package.json
packages/e2e-tests/vite-ssr-esm/server.imba
packages/e2e-tests/vite-ssr-esm/src/App.imba
packages/e2e-tests/vite-ssr-esm/src/counter.imba
packages/e2e-tests/vite-ssr-esm/src/main.imba
packages/e2e-tests/vite-ssr-esm/src/main.js
packages/e2e-tests/vite-ssr-esm/src/shared.imba
packages/e2e-tests/vite-ssr-esm/vite.config.client.js
packages/e2e-tests/vite-ssr-esm/vite.config.server.js
packages/vite-plugin-imba/package-lock.json
packages/vite-plugin-imba/package.json
packages/vite-plugin-imba/src/index.imba

- Add initial rendered CSS in dev in order to fix FOUC
- Add tests for shared and server only CSS

Vite ssr css

---

packages/imba/src/imba/dom/core.imba

fix ssr bug with tags with no dashes e.g <counter>

---

packages/e2e-tests/vite-ssr-esm/package-lock.json
packages/e2e-tests/vite-ssr-esm/package.json
packages/vite-plugin-imba/src/handle-imba-hot-update.imba

This fixes https://github.com/haikyuu/imba-inertia-adapter/issues/8 which was mistakenly reported in another repo :)

fix missing dep + edge case in hmr

---

packages/vscode-imba/scripts/compile-syntaxes.js
packages/vscode-imba/syntaxes/imba.tmLanguage.json

Include JSON tmLanguage in the repo. It's referenced in linguist and [shiki](https://github.com/shikijs/shiki), and it's best to keep this repo as source of truth. Shiki will pull further changes from here

include json tmLanguage in imba

---

packages/imba/typings/styles.modifiers.d.ts

Does anything else need to be done to add these?
Pixel values from https://github.com/imba/imba/blob/a56f050c2737ba5d08d3a4cf851bdd2b0215cdd2/packages/imba/src/compiler/theme.imba#L98

add typings for 2xl and lt-2xl

---

packages/imba/bin/imba.config.mjs
packages/imba/src/vite-plugin/plugin.imba
packages/imba/src/vite-plugin/svg-plugin.imba
packages/imba/src/vite-plugin/utils/compile.ts

Also, adds ci resolution of modules

make cache based on all compilation options

---

packages/imba/src/bundler/cache.imba

The error happens sometimes ... albeit rarely
https://github.com/scrimba/op/actions/runs/9092171377/job/24988979384#step:12:22

catch caching error
