imba/imba

src/imba/dom.static.imba

Implement a reconcile algorithm that will preserve the chain of nodes that are ordered, and rather move the nodes that are *not* in the chain. I think this will have minimal amount of insertions even for completely random re-orderings.

Change reconcile algorithm

---

src/imba/dom.imba
src/imba/dom.legacy.imba
src/imba/tag.imba

- Move ElementTag into tag.imba and make it an abstract class.
- Move defineTag-logic into a class method on ElementTag.
This means you can introduce custom tag hierarchies which
behaves nothing like the HTML-hierarchies.
- SVG now inherits from HTMLElementTag. This probably needs to be
changed a bit, but I don't even know how SVG is supposed to work.
There might be bugs lurking as I removed some other (possibly) legacy
code and variables.

Rework tag class structure

---

src/compiler/cli.imba

Resolves #63 
I'm familiar enough with the Error system (`printCompilerError` and `ImbaParseError`) to appropriately exit the instance. 
However, as it is, the generic/current "EISDIR: illegal operation on a directory" will be thrown.

CLI will find index.imba, if exists within folder

---

.travis.yml
package.json
test/client.js
test/index.imba
test/spec.imba
webpack.config.js

- `npm run test` now properly exits with code=1 when it fails
- `npm run test-phantom` runs the client test in PhantomJS
- A basic .travis.yml which tests on two Node versions + PhantomJS

Travis CI support

---

src/imba/dom/tag.imba

Using dynamic attributes like `<input id=fieldId name=fieldName>` it can be rendering `<input id=undefined ..>` if the `fieldId ` is null.

Blocking id="undefined"

---

src/compiler/nodes.imba
src/compiler/sourcemap.imba
src/imba/dom/event-manager.imba
src/imba/dom/event.imba
src/imba/dom/html.imba
src/imba/dom/index.imba
src/imba/dom/manager.imba
src/imba/dom/pointer.imba
src/imba/dom/reconciler.imba
src/imba/dom/selector.imba
src/imba/dom/server.imba
src/imba/dom/svg.imba
src/imba/dom/tag.imba
src/imba/dom/touch.imba
src/imba/imba.imba
src/imba/index.imba
src/imba/scheduler.imba

This is required for compatibility with ES6 modules and Rollup. Every
file now includes `imba.imba` and extends the Imba-object from there.
`imba/index.imba` is responsible for enforcing the "only a single
Imba-instance per window-scope"

Avoid global variables (for strict mode)

---

readme.md

Currently the logo URL attempts to send user to `https://` version of Imba site.
This results in the following:
Just need to change `https://` to `http://`.

Fix logo URL for proper link to site

---

readme.md

There appears to be some sort of mistake in the readme:
> File icon support is available via the File Icons package **and the code pending in this [issue](https://github.com/file-icons/atom/issues/664) until integrated with the base package.**
The linked issue was resolved ages ago; the icon's been part of the package since [v2.1.14](https://github.com/file-icons/atom/releases/tag/v2.1.14). I've just [finished updating](https://github.com/file-icons/atom/releases/tag/v2.1.29) the Imba icon again to accommodate its new branding.

Remove readme's note about "pending code" in File Icons

---

bin/imbapack

```
TypeError: Cannot read property 'extensions' of undefined
at Object.<anonymous> (/home/damjan/src/imba-router/node_modules/imba/bin/imbapack:27:32)
```
OptionsDefaulter.process in webpack doesn't mutate the input object, it returns a new one

fix crash in imbpack

---

bin/imbapack

Missing one carriage return on Webpack package warning when it has  not being installed by npm

Missing one carriage return on Webpack package

---

test/run-chrome.imba

It was failing with losts of message like the following:
```
(node:55676) UnhandledPromiseRejectionWarning: TypeError: msg.args.map is not a function
at Page.<anonymous> (/Users/ccscanf/src/github.com/imba/imba.git/test/run-chrome.imba:16:29)
at emitOne (events.js:116:13)
at Page.emit (events.js:211:7)
at Page._addConsoleMessage (/Users/ccscanf/src/github.com/imba/imba.git/node_modules/puppeteer/lib/Page.js:628:10)
at Page._onConsoleAPI (/Users/ccscanf/src/github.com/imba/imba.git/node_modules/puppeteer/lib/Page.js:550:10)
at CDPSession.Page.client.on.event (/Users/ccscanf/src/github.com/imba/imba.git/node_modules/puppeteer/lib/Page.js:119:57)
at emitOne (events.js:116:13)
at CDPSession.emit (events.js:211:7)
at CDPSession._onMessage …
```

test: fix run-chrome

---

src/imba/dom/event-manager.imba
test/tags/events.imba

Fixed one bug where passing `0` to a trigger becomes `null`.
Closes: #203 (trigger data is null when supposed to be 0)

Handle data value can result in null

---

lib/cli/imbac.js
src/cli/imbac.imba

This will change the `imbac` output after running it from
```
22:22:43 compile ../../../../../../tmp/x2.imba to ../../../../../../tmp/x2.js 14ms
```
To the following (looks nicer IMHO)
```
22:26:58 compile /tmp/x2.imba to /tmp/x2.js 14ms
```

imbac: resolve the source and destination path in compile output

---

src/imba/dom/tag.imba

The default error message for this is cryptic
```
[...]
imba/dom/tag.js:1207
if (type.substr(0,4) == 'svg:') {
TypeError: Cannot read property 'substr' of undefined
[...]
```
Now it says
```
imba/dom/tag.js:1206
throw ("Expected a valid tag but got falsy type, did you forget to export it?");
^
Expected a valid tag but got falsy type, did you forget to export it?
[...]
```
Closes: #236 (Improve error message when importing private tag)

tag: add error message when tags are used but unexported

---

scripts/bootstrap.js

The bootstrap script was flaky at best and would end up hanging for
hours in some cases. Without giving the user feedback it really looks
like it's maybe doing some serious setup work when in fact it's just
stuck.
The default behavior is every sane now IMHO, where exceptions are
visible but should not occur unless something is wrong on the
file system.
Just in case these changes cause issues I have added several
environment variables that can be used to override the new behavior.
- `VERBOSE=false` - make the script be more silent set.
- `IGNORE_FS_ERRORS=false` - don't show fs exceptions.
- `RESET=true` - destroy the dist directory.
Closes: #259 (v2: More feedback during bootstrap process)

scripts/bootstrap: make the script much more verbose and robust

---

src/compiler/grammar.imba1
src/compiler/nodes.imba1
test/apps/decorators/multiple.imba
test/apps/issues/278.imba
test/apps/syntax/decorators.imba

Changed how decorators are defined. You can now export and import decorators like everything else. Any method starting with `@` is treated as a decorator.
```imba
export def @log target, key, descriptor
let value = descriptor.value
descriptor.value = do
console.log("called {key}")
return value.apply(this,arguments)
return descriptor
```
```imba
import { @log  } from './decorators'
tag user-item
@log def render
<self> ...
```
I'm still trying to come up with a good way to allow passing options to decorators without having to think about whether something is a decorator or a decorator factory (see https://www.typescriptlang.org/docs/handbook/decorators.html). It is subject to change, but right now, any arguments you pass into to decorators will be exposed on self/this in the decorator …

Tweaking decorator syntax

---

src/compiler/grammar.imba1
src/compiler/nodes.imba1
test/apps/syntax/tag-attributes.imba

Allows declaring attributes:
```imba
tag app-item
attr ref-name
let el = <app-item ref-name='one'>
el.getAttribute('ref-name') # one
```
Default values are not supported yet.

Add basic support for declaring tag attributes

---

src/compiler/grammar.imba1
src/compiler/lexer.imba1
src/compiler/nodes.imba1
test/apps/decorators/multiple.imba
test/apps/events/functions.imba
test/apps/rendering/attributes.imba
test/apps/syntax/class-fields.imba
test/apps/syntax/class-inherited.imba
test/apps/syntax/fields.imba

The previous implementation of properties was always creating getters+setters and used weakmaps to store the values. This is slow and too complicated. Now fields use the plain properties (when possible), and they are always set before the constructor like js fields.

Simplified class fields

---

bin/imba.imba

Update the imba cli to show help if run without any arguments. I do this by making the script parameter optional for `imba run <script>` and catch if there is no arguments passed. 
Today:
```bash
➜  imba git:(imba-cli-no-args) ✗ imba
error: missing required argument 'script'
```
Tomorrow:
```
➜  imba git:(imba-cli-no-args) ✗ ./bin/imba
Usage: imba [options] [command]
Options:
-V, --version             output the version number
-h, --help                display help for command
Commands:
run [options] [script]    Imba
build [options] <script>  Build an imba/js/html entrypoint and their
dependencies
serve [options] <script>  Spawn a webserver for an imba/js/html entrypoint
create [project]          Create a new imba project from a template
help [command]            display help for command …
```

Show help if imba cli is run without arguments

---

changelog.md
src/compiler/grammar.imba1
src/compiler/nodes.imba1
src/utils/identifiers.imba
test/apps/syntax/class-decorators.imba
test/proposals/class-decorators/index.imba

Very basic support for class decorators
```imba
def @indexable target
extend class target
def [Symbol.toPrimitive]
#symbol ||= Symbol!
@indexable
class Model
let seen = {}
let item = new Model
seen[item] = true
```

Add experimental support for class decorators

---

packages/imba/src/compiler/grammar.imba1
packages/imba/src/compiler/lexer.imba1
packages/imba/src/compiler/nodes.imba1
packages/imba/src/compiler/selparse.imba
packages/imba/src/compiler/theme.imba
packages/imba/src/imba/dom/context.imba
packages/imba/src/imba/dom/core.imba
packages/imba/src/imba/dom/core.web.imba
packages/imba/src/imba/dom/keyed-list.imba
packages/imba/src/imba/dom/mount.imba
packages/imba/src/utils/spec.imba
packages/imba/test/apps/style/scoping.imba
packages/imba/test/apps/style/specificity-new.imba
packages/imba/test/apps/style/specificity-scoped.imba
packages/imba/test/apps/style/specificity.imba
packages/imba/test/spec.imba
packages/imba/vendor/css-selector-parser.js
packages/vscode-imba/package.json
packages/vscode-imba/syntaxes/imba.YAML-tmLanguage
packages/vscode-imba/syntaxes/imba.tmLanguage

Reworked specificity for generated style rules to be more intuitive. Styles in tag declaration now has lower precedence than any class-selectors. The actual rules for specificity might change before launch (will involve community re. this).
This will potentially result in broken styles for projects when upgrading. Will write a more thorough article about what the changes are, and which previous styling patterns might now break.

Css specificity

---

packages/e2e-tests/vite-ssr-esm/__tests__/vite-ssr-esm.spec.ts
packages/e2e-tests/vite-ssr-esm/src/main.imba
packages/imba/src/compiler/nodes.imba1
packages/vite-plugin-imba/src/utils/compile.ts

- Add a `resolveColors` option to the compiler to allow resolving colors even when `styles :"extern"` 
- Compile imba files once

add resolveColors option + only compile once

---

packages/imba/bin/imba-create.imba

Module template: https://github.com/imba/imba-module-template
Tested and working with React, Vue, and Svelte.
It deserves its own template because:
- Incremental adoption is important, the fact that imba uses actual custom elements is a selling point.
- Several additions needed to be made to `vite.config.js`, `package.json`, and `main.imba`.

add module template to cli

---

packages/imba/src/bundler/config.imba

To allow import of webassembly assets(.wasm), this will at least add the webassembly file to the assets!
Adding the webassembly extension to the loader list allows initial use of the webassembly with Imba. Without this extension the code does not transpile
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] I have read the **CONTRIBUTING** document.
- [ x] I have updated/added documentation affected by my changes.
- [ x] I have added tests to cover my changes.

Initial Webassembly support

---

packages/imba/typings/styles.d.ts

The documentation for the ea/ease property had an incorrect spelling of skew-y in its description.
<p align="center">
</p>
After some discussion with @familyfriendlymikey over the Discord server, we came up with a solution. This PR not only corrects the spelling error, but also improves the overall readability of both the code and the docs by updating to the metadata/comments/docs for the two-letter easing shorthands (ea, eb, ec, et, and eo), making it easier for developers to understand and utilize these properties.
<p align="center">
</p>
Hope this clears developers' doubts more effectively and brings more Imba apps with cool transitions to life. 🎉

Fix and improve docs/metadata on easing typings

---

packages/imba/src/imba/dom/fragment.imba

closes https://github.com/imba/imba/issues/680

fix slots error with web components

---

packages/imba/bin/imba.imba

In the vite build, the `--web` option is not used to determine whether a client-only build should be done, so an html entry point is required.
I have made a simple patch that should force a client build when the `--web` CLI flag is provided, bringing the functionality closer to the default imba bundler.

fix: --web flag should force a vite client build

---

packages/imba/src/imba/events/intersect.imba

When I render a component serverside with an intersect event, it causes an error as intersection observer is only available in a browser context.

change intersect to only run on web

---

packages/e2e-tests/hmr/package-lock.json
packages/e2e-tests/imba-config-file/package-lock.json
packages/e2e-tests/imba-resolve-config-inline/package-lock.json
packages/e2e-tests/imba-serve-file/package-lock.json
packages/e2e-tests/imba-serve/package-lock.json
packages/e2e-tests/ionic-app/package-lock.json
packages/e2e-tests/package-lock.json
packages/e2e-tests/server-custom-vite-config/package-lock.json
packages/e2e-tests/vite-duplicate-styles-bug/package-lock.json
packages/e2e-tests/vite-import-svg/package-lock.json
packages/e2e-tests/vite-middleware/__tests__/vite-middleware.spec.ts
packages/e2e-tests/vite-middleware/package-lock.json
packages/e2e-tests/vite-ssr-esm/package-lock.json
packages/imba/src/vite-plugin/plugin.imba

Vite has built-in caching in memory. This fs caching improves the "start-time" of the plugin. 3 times faster in a big project like OP

[vite-plugin] cache plugin transformation in fs

---

packages/imba/src/compiler/selparse.imba
packages/imba/vendor/css-selector-parser.js

Syntax is currently: `@c-article230`, `c@c-article!20`
Here is a complete example:
```
tag my-app
<self>
<div[w:100px container:article / inline-size]>
css
span @c-article39 c:red4 fs:111cqw
<span[d@300:block]> "I should be red"
imba.mount <my-app>
```
Note that the container query units are available `cqw` is container query width. + `cqh`, `cqi` inline-size and `cqb` for block-size.

experimental feature: container queries

---

.github/workflows/e2e.yml
packages/imba/src/bundler/bundle.imba

This PR fixes an issue with running `imba --web` where it didn't copy the public assets to the build directory.
(It also unblocks running e2e tests due to deprecated actions package)

copy public files when running imba with --web flag
